<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUudkHz3\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUudkHz3/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUudkHz3.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUudkHz3\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUudkHz3\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'UudkHz3',
    'container.build_id' => '14fbc12c',
    'container.build_time' => 1523615662,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUudkHz3');
